name: Terraform CI

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Init Terraform
        working-directory: day-2-main-config-files
        run: terraform init

      - name: Terraform Plan
        working-directory: day-2-main-config-files
        run: terraform plan
